#!/bin/bash
#set -e
set -x

ROOT_DIR=`pwd`

function get_tar_cmd
{
    local f=$1
    local ext=${f##*.}
    local cmd=''
    if [ "$ext" = "bz2" ];then
        cmd='-jx'
    elif [ "$ext" = "gz" ];then
        cmd='-zx'
    elif [ "$ext" = "xz" ];then
        cmd='-Jx'
    fi
    echo $cmd
}

function compile_lib
{
    local FILE=$1
    local BCMD=$2
    local BDIR=${FILE%.tar.*}
    if [ -e $BDIR ];then
        rm -r $BDIR
    fi
    mkdir "$BDIR"

    local cmd=$(get_tar_cmd $FILE)
    cd "$BDIR" && \
        cat "../$FILE" |tar $cmd --strip-components=1 && \
        eval $BCMD && \
        make && \
        make install && \
        make clean 

    cd $ROOT_DIR
}


#compile external libs
X264_ENABLED=0
X265_ENABLED=0
VPX_ENABLED=0
FDKAAC_ENABLED=0
XVID_ENABLED=0
LIBFRIBIDI_ENABLED=0
FREETYPE_ENABLED=0
FONTCONFIG_ENABLED=1
LIBASS_ENABLED=0
#x264
if [ $X264_ENABLED = "1" ];then
    X264_FILE="x264-snapshot-20160829-2245-stable.tar.bz2"
    X264_CMD='./configure --prefix="`pwd`" --disable-cli --enable-static --disable-shared'
    #X264_PC='x264.pc'
    compile_lib "$X264_FILE" "$X264_CMD" #"$X264_PC"
fi

#x265
if [ $X265_ENABLED = "1" ];then
    X265_FILE="x265_2.0.tar.gz"
    X265_CMD='cmake -G "Unix Makefiles" "`pwd`/source" -DCMAKE_INSTALL_PREFIX="`pwd`" -DENABLE_STATIC:bool=on -DENABLE_SHARED:bool=off -DENABLE_CLI:bool=off'
    #X265_PC='x265.pc'
    compile_lib "$X265_FILE" "$X265_CMD" #"$X265_PC"
fi

#vpx
if [ $VPX_ENABLED = "1" ];then
    VPX_FILE="libvpx-1.6.0.tar.bz2"
    VPX_CMD='./configure --prefix="`pwd`" --enable-vp8 --enable-vp9  --disable-shared --enable-static --disable-examples --disable-docs'
    #VPX_PC='vpx.pc'
    compile_lib "$VPX_FILE" "$VPX_CMD" #"$VPX_PC"
fi

#fdk-aac
if [ $FDKAAC_ENABLED = "1" ];then
    FDKAAC_FILE="fdk-aac-0.1.4.tar.gz"
    FDKAAC_CMD='./autogen.sh && ./configure --prefix="`pwd`" --disable-shared '
    #FDKAAC_PC='fdk-aac.pc'
    compile_lib "$FDKAAC_FILE" "$FDKAAC_CMD" #"$FDKAAC_PC"
fi

#xvid
if [ $XVID_ENABLED = "1" ];then
    XVID_FILE="xvidcore-1.3.4.tar.gz"
    XVID_CMD='cd build/generic && ./configure --prefix="`pwd`" --bindir="`pwd`/bin" --datadir="`pwd`"'
    compile_lib "$XVID_FILE" "$XVID_CMD"
fi

#fribidi
if [ $LIBFRIBIDI_ENABLED = "1" ];then
    LIBFRIBIDI_FILE="fribidi-0.19.7.tar.bz2"
    LIBFRIBIDI_CMD='mkdir build_dir&&cd build_dir&&mkdir exec_dir&&../configure --prefix="`pwd`" --exec-prefix="`pwd`/exec_dir" --with-glib=no --disable-shared --enable-static'
    compile_lib "$LIBFRIBIDI_FILE" "$LIBFRIBIDI_CMD"
fi

#freetype
if [ $FREETYPE_ENABLED = "1" ];then
    FREETYPE_FILE="freetype-2.6.5.tar.gz"
    FREETYPE_CMD='mkdir build_dir&&cd build_dir&&../configure --prefix=`pwd` --disable-shared --enable-static --with-sysroot=`pwd` --with-zlib=no --with-bzip2=no --with-png=no --with-harfbuzz=no'
    compile_lib "$FREETYPE_FILE" "$FREETYPE_CMD"
fi

#expat
#mkdir build_dir&&cd build_dir&&../configure --prefix=`pwd` --enable-static --disable-shared


#fontconfig
if [ $FONTCONFIG_ENABLED = "1" ];then
    FONTCONFIG_FILE="fontconfig-2.12.0.tar.gz"
    FONTCONFIG_CMD='./configure --prefix=`pwd` --disable-shared --enable-static '
    compile_lib "$FONTCONFIG_FILE" "$FONTCONFIG_CMD"
fi
#libass
if [ $LIBASS_ENABLED = "1" ];then
    LIBASS_FILE="libass-0.12.2.tar.xz"
    LIBASS_CMD='./configure --prefix=`pwd` --disable-shared --enable-static'
    compile_lib "$LIBASS_FILE" "$LIBASS_CMD"
fi

